### PR TITLE
Make stargazers and forks stick to bottom of repo cards

### LINKED ISSUE #25: Improve style by making stargazers and forks stick to bottom of repo card
Here is how GitHub repository cards are laid out:

screenshot 2019-02-22 at 17 11 24

The language tag, stargazers and forks are sticking to the bottom of the card.

The current stylesheet that can be found in `assets/styles.scss` is not consistent with the GitHub layout.

In order to do that, I'd suggest making the repo cards `position: relative` and the `div` element containing the stargazers and forks `position: absolute; bottom: 10px` to achieve a similar look.

The result of doing that can be seen on [my fork](https://ullaakut.github.io/)

### PR DESCRIPTION
**Pull request by Ullaakut**
## Goal of this PR

This pull request makes repository cards behave like the repository cards that can be seen on GitHub, by having the bottom row (with stargazers and forks) stick to the bottom.

Here is an example of what it looks like on `master`

screenshot 2019-02-23 at 05 59 38

And of the layout proposed in this PR

screenshot 2019-02-23 at 06 00 54

In order to achieve that, three minor changes were added:

* The repo card itself gets a new `position: relative` CSS property
* The `div` that wraps the stargazers and forks gets the `position: absolute` and `bottom: 10px` CSS properties
* The `div` that wraps the description has its `mb-2` (margin bottom 2) class replaced with a `mb-4` in order to compensate for the bottom row now being absolute and not pushing the repository card's height anymore.

Fixes #25 

## How to test it

* Checkout this branch
* `bundle exec jekyll serve`
* Visit `http://127.0.0.1:4000` and ensure the cards are behaving properly, with different viewport sizes (from desktop to mobile)

### CODE REVIEW

**Comment by brandonrosage** [comment]
Great catch, @Ullaakut! I've added a commit that does a couple things:

1. Replaces the absolute positioning approach with a flexbox approach.
2. Removes the CSS your original commit added, for two reasons: Primer, the CSS framework included in the project, includes utility classes that already offer the utility yours did. And the flexbox approach uses existing flexbox utility classes within Primer.

Cool?

**Comment by Ullaakut** [comment]
@brandonrosage Awesome! Thanks 🎉

**Comment by Ullaakut** [comment]
Mh, it seems I broke the branch while rebasing to fix the conflicts 😅

Fixing this right now. Sorry about that :)

**Comment by brandonrosage** [comment]
I think we got it pegged 👍 Merge Time ™️

**Pull request merged**
