### PR TITLE
Escape @ symbol in yaml files

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by aadibajpai** [comment]
Some accounts don't have @. https://medium.com/ycombinator

**Comment by SUPERCILEX** [comment]
That's a publication though, isn't the idea to showcase _your_ profile? The problem is that the @ symbol is illegal without quotes:
```
found character that cannot start any token while scanning for the next token at line 30 column 11
```

**Comment by aadibajpai** [comment]
Sure, but what if someone own a publication they want to showcase.

**Comment by SUPERCILEX** [comment]
I disagree, but 🤷‍♂️

**Comment by aadibajpai** [comment]
@SUPERCILEX I'm not sure either which would be the best approach. It's also possible to remove the @ and mention somewhere. I see that it works for publications when you add the @ symbol as well as without it 😃

**Comment by SUPERCILEX** [comment]
So are you saying I should revert back to the first approach? I personally prefer that since it'll work for most people.

**Comment by aadibajpai** [comment]
Yes.

**Comment by SUPERCILEX** [comment]
Awesome, done!

**Pull request merged**
