### PR TITLE
Removing the limit of topics list

### PR DESCRIPTION
**Pull request by Ouadie**
The first thing I wanted to do after running the website is to add multiple interests. I guess adding the limit of interests as a config will reduce changes for a lot of users.
**Update**
Limit removed since the user adds the topics it makes sense to display all topics.

### CODE REVIEW

**Comment by Ullaakut** [comment]
Hi @Ouadie, thanks for the contribution :)

I might be missing something, but what's the point of configuring a limit for interests, since interests have to be manually added to the configuration in the first place? 🤔

**Comment by Ouadie** [comment]
Hi @Ullaakut, when a user fork the repo then starts editing the config by adding more topics, 6 for example, only 4 will be visible because of the hardcoded limit value in `interests.html`. For my case, I added 9 topics and I couldn't get why only 4 are displayed. Then I had to change the code to make the 9 topics visible. Yes users add topics, but it is easier to change the limit in the config instead of the `interests.html`

**Comment by Ullaakut** [comment]
Ah, I see. Then actually the real solution would probably be to remove the limit entirely, don't you think?

Since users already have to manually add interests in their config, it doesn't make sense to then limit the number that are shown on the website, in my opinion. WDYT?

**Comment by Ouadie** [comment]
Or we can remove the limit completely, makes sense.

**Comment by Ullaakut** [comment]
Nice job @Ouadie! Please update the PR name and description to fit those changes 🙏🏽

**Comment by Ouadie** [comment]
Done

**Pull request merged**
