### PR TITLE
feat: sort repo by pushed date

### PR DESCRIPTION
**Pull request by AungMyoKyaw**

### CODE REVIEW

**Comment by brandonrosage** [comment]
Because we have [another PR](https://github.com/github/personal-website/pull/19) suggesting that **_stars_** be the default sorting method, my thinking here is that we default to the most intuitive and generic sorting method, and then either offer a `_config.yml` parameter or docs describing the available sorting values.

I think the method you're proposing -- `pushed_date` -- is the most intuitive. It's also consistent with other GitHub repo listings.

Any other thoughts?

**Comment by AungMyoKyaw** [comment]
Yes I agree with you. Sorting by pushed_date is better option.

**Comment by tterb** [comment]
If possible, I feel like a `_config.yml` parameter would be an ideal solution since that could cater to all preferences, though I agree that `pushed_date` would be an intuitive default.  
Additionally, it would be nice if there was a parameter that would also allow users to exclude certain repositories, in the case of inactive or no longer maintained projects.

**Comment by brandonrosage** [comment]
@tterb I agree that we should support more detailed configuration via `_config.yml`. I'll help do that in a separate PR, but get the ball rolling by merging this one 👍 

It's a solid default.

**Pull request merged**
